version: '3'

services:
  inanna-backend:
    build: .
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - database
  
  database:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root12345.
      MYSQL_DATABASE: inanna_db
      MYSQL_TCP_PORT: 3307  # Change the port to avoid conflicts
    ports:
      - "3307:3307"  # Change the port to avoid conflicts
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
