[build]
  command = "yarn install && yarn build"
  functions = "functions"

[functions]

  [functions.register]
  external_node_modules = [
    "module-one",
    "module-two"
  ]

[functions.login]
  external_node_modules = [
    "module-one",
    "module-two"
  ]

[functions.logout]
  external_node_modules = [
    "module-one",
    "module-two"
  ]

[functions.fetchUsers]
  external_node_modules = [
    "module-one",
    "module-two"
  ]

[functions.fetchCompanies]
  external_node_modules = [
    "module-one",
    "module-two"
  ]

[functions.fetchProducts]
  external_node_modules = [
    "module-one",
    "module-two"
  ]

[functions.createProduct]
  external_node_modules = [
    "module-one",
    "module-two"
  ]