[build]
  command = "yarn start"
  functions = "functions"

[functions]
  register = "node functions/register.js"
  login = "node functions/login.js"
  logout = "node functions/logout.js"
  fetchUsers = "node functions/fetchUsers.js"
  fetchCompanies = "node functions/fetchCompanies.js"
  fetchProducts = "node functions/fetchProducts.js"
  createProduct = "node functions/createProduct.js"